[build]
  command = "npm run typecheck"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@oxc-project/runtime",
    "lightningcss",
    "oxc-minify",
    "oxc-parser",
    "oxc-resolver",
    "oxc-transform",
  ]
  included_files = [
    "app/**",
    "public/**",
    "tsconfig.json",
    "node_modules/@oxc-project/**",
    "node_modules/@oxc-minify/**",
    "node_modules/@oxc-parser/**",
    "node_modules/@oxc-resolver/**",
    "node_modules/@oxc-transform/**",
    "node_modules/lightningcss/**",
    "node_modules/lightningcss-*/**",
    "node_modules/remix/dist/**",
  ]
