import { css } from 'remix/ui'

import { focusRing, theme } from '../../../../theme/styles.ts'

export const projectActionLinkStyle = css({
  width: '34px',
  height: '34px',
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  position: 'relative',
  borderRadius: theme.radius.md,
  color: theme.colors.text.link,
  border: `1px solid ${theme.colors.border.subtle}`,
  background: 'rgb(255 255 255 / 0.035)',
  transition: 'color 160ms ease, border-color 160ms ease, background 160ms ease',
  '&::after': {
    content: 'attr(data-tooltip)',
    position: 'absolute',
    left: '50%',
    bottom: 'calc(100% + 10px)',
    zIndex: 5,
    transform: 'translateX(-50%) translateY(4px)',
    opacity: 0,
    pointerEvents: 'none',
    whiteSpace: 'nowrap',
    padding: '5px 8px',
    borderRadius: theme.radius.sm,
    border: `1px solid ${theme.colors.border.subtle}`,
    color: theme.colors.text.primary,
    background: theme.surface.lvl3,
    boxShadow: theme.shadow.sm,
    fontSize: theme.fontSize.xs,
    fontWeight: theme.fontWeight.medium,
    transition: 'opacity 140ms ease, transform 140ms ease',
  },
  '&::before': {
    content: '""',
    position: 'absolute',
    left: '50%',
    bottom: 'calc(100% + 5px)',
    zIndex: 5,
    width: '8px',
    height: '8px',
    transform: 'translateX(-50%) translateY(4px) rotate(45deg)',
    opacity: 0,
    pointerEvents: 'none',
    background: theme.surface.lvl3,
    borderRight: `1px solid ${theme.colors.border.subtle}`,
    borderBottom: `1px solid ${theme.colors.border.subtle}`,
    transition: 'opacity 140ms ease, transform 140ms ease',
  },
  '&:hover': {
    color: theme.colors.action.primary.backgroundHover,
    borderColor: theme.colors.text.link,
    background: 'rgb(255 255 255 / 0.06)',
  },
  '&:hover::after, &:focus-visible::after': {
    opacity: 1,
    transform: 'translateX(-50%) translateY(0)',
  },
  '&:hover::before, &:focus-visible::before': {
    opacity: 1,
    transform: 'translateX(-50%) translateY(0) rotate(45deg)',
  },
  '&:focus-visible': focusRing,
})
